Adds poetry_args and environment inputs to pytest

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -1,22 +1,32 @@
-name: 🐍 pytest
+name: 🐍 Pytest
 
 on:
   workflow_call:
     inputs:
       python_version:
         description: The version of python to setup
-        default: 3.11
         type: string
+        default: 3.11
 
+      environment:
+        description: The name of the environment to deploy
+        type: string
+        default: Codecov
+
+      poetry_args:
+        description: Additional args to pass to poetry
+        type: string
+        default: --with test
+  
       pytest_args:
-        description: Additional args to pass to pytest.
+        description: Additional args to pass to pytest
         type: string
 
 jobs:
   run_pytest:
-    name: 🐍 pytest
+    name: 🐍 Run pytest and upload coverage report
     runs-on: ubuntu-latest
-    environment: codecov
+    environment: ${{ inputs.environment }}
 
     steps:
       - name: 📰 Checkout
@@ -36,19 +46,21 @@ jobs:
         uses: actions/cache@v3
         with:
           path: .venv
-          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
+          key: venv-test-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
 
       - name: 🏋 Download dependencies
         if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
-        run: poetry install --no-interaction --no-root
+        run: poetry install --no-interaction --no-root ${{ inputs.poetry_args }}
 
       - name: 🏗️ Install dependencies
-        run: poetry install --no-interaction
+        run: poetry install --no-interaction ${{ inputs.poetry_args }}
 
       - name: 🧪 Run pytest suite
         run: poetry run pytest -v --cov --cov-report lcov ${{ inputs.pytest_args }}
 
       - name: 📈 Uploade coverage report
+        # run this step, even if the tests fail
+        if: success() || failure()
         uses: codecov/codecov-action@v3
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
